<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Cloudinary Configuration
    |--------------------------------------------------------------------------
    |
    | An HTTP or HTTPS URL to notify your application (a webhook) when the
    | process of uploads, deletes, and any API that accepts
    | notification_url has completed.
    |
    */

    'notification_url' => env('CLOUDINARY_NOTIFICATION_URL'),

    /*
    |--------------------------------------------------------------------------
    | Cloudinary Cloud URL
    |--------------------------------------------------------------------------
    |
    | This is the Cloudinary URL containing your cloud name, API key and
    | API secret. This should be set in your .env file.
    |
    */

    'cloud_url' => env('CLOUDINARY_URL'),

    /*
    |--------------------------------------------------------------------------
    | Cloudinary Upload Preset
    |--------------------------------------------------------------------------
    |
    | This is the name of the unsigned upload preset. You can create one
    | in the Cloudinary dashboard under Settings > Upload > Upload presets.
    |
    */

    'upload_preset' => env('CLOUDINARY_UPLOAD_PRESET'),

    /*
    |--------------------------------------------------------------------------
    | Cloudinary Secure
    |--------------------------------------------------------------------------
    |
    | When set to true, all URLs generated by Cloudinary will use HTTPS.
    |
    */

    'secure' => env('CLOUDINARY_SECURE', true),

    /*
    |--------------------------------------------------------------------------
    | Default Folder
    |--------------------------------------------------------------------------
    |
    | The default folder where files will be uploaded to.
    |
    */

    'folder' => env('CLOUDINARY_FOLDER', 'cuesports'),

];
